/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const UserProfile = IDL.Record({
  'classSection' : IDL.Opt(IDL.Text),
  'name' : IDL.Text,
  'registrationNumber' : IDL.Opt(IDL.Text),
});
export const Document = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'createdAt' : IDL.Int,
  'section' : IDL.Text,
  'description' : IDL.Text,
  'fileUrl' : IDL.Text,
});
export const OTPEntry = IDL.Record({
  'otp' : IDL.Text,
  'classSection' : IDL.Text,
  'createdAt' : IDL.Int,
  'registrationNumber' : IDL.Text,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addDocument' : IDL.Func([IDL.Text, IDL.Text, IDL.Text, IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'deleteDocument' : IDL.Func([IDL.Nat], [], []),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getDocumentsBySection' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(Document)],
      ['query'],
    ),
  'getPendingOTPs' : IDL.Func([], [IDL.Vec(OTPEntry)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'requestOTP' : IDL.Func([IDL.Text, IDL.Text], [OTPEntry], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'verifyOTP' : IDL.Func([IDL.Text, IDL.Text], [IDL.Bool], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const UserProfile = IDL.Record({
    'classSection' : IDL.Opt(IDL.Text),
    'name' : IDL.Text,
    'registrationNumber' : IDL.Opt(IDL.Text),
  });
  const Document = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'createdAt' : IDL.Int,
    'section' : IDL.Text,
    'description' : IDL.Text,
    'fileUrl' : IDL.Text,
  });
  const OTPEntry = IDL.Record({
    'otp' : IDL.Text,
    'classSection' : IDL.Text,
    'createdAt' : IDL.Int,
    'registrationNumber' : IDL.Text,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addDocument' : IDL.Func([IDL.Text, IDL.Text, IDL.Text, IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'deleteDocument' : IDL.Func([IDL.Nat], [], []),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getDocumentsBySection' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(Document)],
        ['query'],
      ),
    'getPendingOTPs' : IDL.Func([], [IDL.Vec(OTPEntry)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'requestOTP' : IDL.Func([IDL.Text, IDL.Text], [OTPEntry], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'verifyOTP' : IDL.Func([IDL.Text, IDL.Text], [IDL.Bool], []),
  });
};

export const init = ({ IDL }) => { return []; };